language: csharp
os: linux
dist: xenial
mono: latest
dotnet: 5.0.102 # to update this value in the future, try `dotnet --list-sdks` as a start
git:
  depth: false
addons:
  apt:
    update: true

before_install: sudo apt-get -y install tree

install:
- dotnet restore
- tree -a .

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- dotnet build RomanizationNet.sln --configuration Release --no-restore
- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov Romanization.Tests/Romanization.Tests.csproj

after_script:
- cat Romanization.Tests/coverage.net5.0.info
- ./cc-test-reporter format-coverage --input-type lcov --output Romanization.Tests/codeclimate.json Romanization.Tests/coverage.net5.0.info
- cat Romanization.Tests/codeclimate.json
- ./cc-test-reporter upload-coverage --input Romanization.Tests/codeclimate.json

before_deploy: echo "Installing docfx..." && wget -q "https://github.com/dotnet/docfx/releases/download/v2.56.6/docfx.zip" && unzip -q -o -d ./docfx docfx.zip

deploy:
  provider: script
  cleanup: false
  script: chmod +x ./Scripts/deploy.sh && bash ./Scripts/deploy.sh $NUGET_API_KEY $NUGET_SOURCE $GH_API_KEY $GH_PACKAGES_SOURCE
  on:
    branch: main

after_deploy: chmod +x ./Scripts/updateDocs.sh && bash ./Scripts/updateDocs.sh $GH_API_KEY
